import test from 'node:test';import assert from 'node:assert/strict';
import {MotionInput,restingSpecificForce,boardAcceleration,capAcceleration,flickAcceleration,physicalGravity} from '../dist/motion.js';
import {newBall,advance,STEP,CONTACTS} from '../dist/physics.js';import {G} from '../dist/materials.js';
const free={terrain:false,patches:false,walls:[],holes:[],goal:false,bounds:false,air:false};
test('gravity subtraction is correct at pitched neutral and four screen rotations',()=>{for(const beta of [0,35,-30])for(const gamma of [0,18,-12]){const raw=restingSpecificForce(beta,gamma);assert.ok(Math.abs(Math.hypot(raw.x,raw.y,raw.z)-G)<1e-12);for(const angle of [0,90,180,270]){const a=boardAcceleration(raw,beta,gamma,angle);assert.ok(Math.hypot(a.x,a.y,a.z)<1e-12);}}});
test('30 degrees in 0.3 seconds with interleaved 60 Hz streams stays below 0.3 m/s² synthetic leakage',()=>{const input=new MotionInput();let worst=0;for(let i=0;i<=18;i++){const t=i*1000/60,beta=35+i*30/18;input.orientation(beta,10,t);const motionTime=t+1000/120,b=35+Math.min(30,(motionTime/300)*30);const a=input.ingest(restingSpecificForce(b,10),motionTime,0);if(a)worst=Math.max(worst,Math.hypot(a.x,a.y));}assert.ok(worst<.3,'synthetic leakage '+worst);});
test('sample-and-hold preserves impulses across frames; stale and resumed samples do not persist',()=>{const m=new MotionInput();m.orientation(0,0,0);m.ingest({x:2,y:0,z:G},10);m.ingest({x:4,y:0,z:G},30);const impulse=m.segments(10,50).reduce((s,p)=>s+p.dt*p.a.x,0);assert.ok(Math.abs(impulse-.12)<1e-12);assert.equal(m.at(131).x,0);m.resetHold();assert.equal(m.at(40).x,0);});
test('3g cap preserves direction and clipping report makes no hardware range claim',()=>{const a=capAcceleration({x:50,y:-25,z:0});assert.ok(a.capped);assert.ok(Math.abs(Math.hypot(a.x,a.y,a.z)-3*G)<1e-12);assert.equal(a.x/a.y,-2);const m=new MotionInput();m.orientation(0,0,0);for(let i=0;i<8;i++)m.ingest({x:2*G,y:0,z:G},i*16);assert.ok(m.clipSuspected);assert.match(m.report().hardwareRange,/not exposed/);const raw=Object.create({get x(){return 2*G;},get y(){return 0;},get z(){return G;}});m.ingest(raw,150);assert.deepEqual(m.report().samples.at(-1).raw,{x:2*G,y:0,z:G});});
test('finite 0.4 m/s flick and 30 ms stop separates and reproduces the 2.15 mm analytic hop',()=>{const b=newBall(),lift=.15,stop=.03,speed=.4;let first=null,peak=0;const dt=.001;for(let i=0;i<1000;i++){const a=flickAcceleration(i*dt,speed,lift,stop);advance(b,{x:0,y:0},dt,{...free,acceleration:a,floorProfile:{...CONTACTS.steel.wood,eRef:0}});if(!b.grounded&&first===null)first=b.time-dt;peak=Math.max(peak,b.z-b.r);}const exact=speed*speed/(2*G)-speed*stop/2;assert.ok(Math.abs(first-lift)<STEP*1.1);assert.ok(Math.abs(peak-exact)/exact<.05,`${peak} vs ${exact}`);});
test('weight reduction changes the grip threshold without a gesture or jump command',()=>{const a=newBall('steel','ice'),b=newBall('steel','ice');for(let i=0;i<80;i++){advance(a,{x:5,y:0},STEP,free);advance(b,{x:5,y:0},STEP,{...free,acceleration:{x:0,y:0,z:-.5*G}});}assert.ok(a.slip<1e-8);assert.ok(b.slip>.02);});

test('pitched calibration preserves free-fall equivalence in the virtual board frame',()=>{for(const beta of [0,35,60])for(const angle of [0,90,180,270]){const b=newBall(),a=boardAcceleration({x:0,y:0,z:0},beta,12,angle);a.sourceGravity=physicalGravity(beta,12,angle);advance(b,{x:4,y:-3},STEP,{...free,acceleration:a});assert.ok(Math.hypot(b.vx,b.vy,b.vz)<1e-10);assert.ok(b.normalLoad<1e-10);assert.equal(b.grounded,false);}});
