import {writeFileSync} from 'node:fs';
import {makeLandscape,levelFromLandscape} from '../dist/landscape.js';
import {structural,pocketTrial,botSuite,rejectedHandmade} from './validate-relief.mjs';
const candidates=[];let selected=null;
for(let seed=371;seed<379;seed++){
 const level=levelFromLandscape(makeLandscape(seed)),shape=structural(level);
 if(!shape.accepted){candidates.push({seed,accepted:false,reason:'geometry or route slope',shape});continue;}
 const pocket=pocketTrial(level);if(!pocket.accepted){candidates.push({seed,accepted:false,reason:'pocket confinement or escape',pocket});continue;}
 const pilot=botSuite(level,1);if(!pilot.accepted){candidates.push({seed,accepted:false,reason:'route pilot',successes:pilot.scenarios.map(s=>[s.material,s.successes])});continue;}
 const bots=botSuite(level,10);if(!bots.accepted){candidates.push({seed,accepted:false,reason:'route acceptance',bots});continue;}
 selected={seed,accepted:true,shape,pocket,bots};candidates.push(selected);break;
}
if(!selected){writeFileSync(new URL('../dist/relief-generation.json',import.meta.url),JSON.stringify({selectedSeed:null,candidates},null,2)+'\n');throw Error('No candidate accepted; the previous selected level is preserved.');}
const blocked=rejectedHandmade(levelFromLandscape(makeLandscape(selected.seed)));
if(!blocked.rejected)throw Error('The validator failed to reject the blocked handmade level.');
writeFileSync(new URL('../dist/relief-config.js',import.meta.url),`// Generated by the relief validator. Phone acceptance remains pending.\nexport const RELIEF_SEED=${selected.seed};\n`);
writeFileSync(new URL('../dist/relief-generation.json',import.meta.url),JSON.stringify({selectedSeed:selected.seed,candidates,rejectedHandmade:blocked},null,2)+'\n');
console.log(`Selected seed ${selected.seed}; ${candidates.length} generated candidate(s); blocked handmade board rejected.`);
